config/routes.rb
Testapp2::Application.routes.draw do

 root :to => 'staticpages#index'
 resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :hour, :emotion, :learned, :image
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = Pic.create(params[:pic])
		redirect_to pics_path
	end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	
	def index
		@pics = Pic.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

    <div class="navbar navbar-inverse">
	    <div class="navbar-inner">
			    <div class="container">
			     
			    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    </a>
			     
			    <!-- Be sure to leave the brand out there if you want it shown -->
			    <%= link_to 'Ankit\'s Project', root_path, :class => 'brand' %> 
			     
			    <!-- Everything you want hidden at 940px or less, place within here -->
			    <div class="nav-collapse collapse">
			    <!-- .nav, .navbar-search, .navbar-form, etc -->
				    <ul class="nav">
			    	<li><%= link_to 'My App', pics_path %></li>
 			    	<li><%= link_to 'Add a Pic', new_pic_path %></li>
				    </ul>
			    </div>
		     
		    </div>
	    </div>
    </div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<div class="my-wrapper">
<h1 class="custom-font-1 offset0">My Pics</h1>
<br/>

<% @pics.each do |pic| %>
	<div class="stolen-surfbox span3 offset0">
		<h2 class="custom-font-1">
			Hour <%= pic.hour %>
		</h2>

		<div>
			<%= image_tag pic.image %>
		</div>

		<h3 class="custom-font-2">
			I feel <%= pic.emotion %>.
		</h3>

		<p class="custom-font-3">
			I learned that <%= pic.learned %>.
		</p>
	</div>

<% end %>

</div>

app/views/pics/new.html.erb
<div class="my-wrapper text-center">
<h1>Upload Your Pic</h1>
<br/>
<div class="stolen-surfbox span0 centered-horizontal-newbox">
<%= simple_form_for @pic do |f| %>

	<%= f.input :hour, :label_html=> { :class=>'custom-font-2' }, :input_html=>{:class=>'newbox-width'}%>

	<%= f.input :image, :as => :file, :label_html=> { :class=>'custom-font-2' } %>

	<%= f.input :emotion, :label =>'Mood', :label_html=> {:class=>'custom-font-2'}, :input_html=>{:class=>'newbox-width'}%>

	<%= f.input :learned, :label_html => {:class =>'custom-font-2'}, :input_html=>{:class=>'newbox-height newbox-width'} %>

	<%= submit_tag "Save Picture", :class=>'btn btn-primary'%>

<% end %>
</div>

app/views/staticpages/index.html.erb
<div class="span6 offset0 text-center stolen-surfbox centered-homebox">
	
	<h1 class="custom-font-1">Hello I'm Ankit!</h1>
	
	<h2 class="custom-font-2"> I'm having a lot of fun learning how to code at the Firehose Weekend</h2>

	<%= link_to("Launch App", pics_path, :class => 'btn btn-large btn-primary') %>

</div>